apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nageshreddy-deployment
  namespace: nageshreddy
spec:
  selector:
    matchLabels:
      app: nageshreddy
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nageshreddy
    spec:
      containers:
      - name: nageshreddy
        image: 349948765351.dkr.ecr.ap-south-1.amazonaws.com/nageshreddy:latest
        ports:
        - containerPort: 80





